### ISSUE TITLE
configuration docs don't exist: https://github.com/solo-io/squash-initial/

### ISSUE THREAD

**Issue by squillace** [solo-io/squash-vscode#3]
Hi there. In the example doc: https://github.com/solo-io/squash-vscode/blob/master/docs/example-app-kubernetes.md it says: 

`Squash server & client installed.` where the link is to: https://github.com/solo-io/squash-initial/tree/master/docs/install#command-line-interface-cli. Unfortunately, the entire repo solo-io/squash-initial doesn't seem to be public. 

Have I missed something?

**Comment by ilevine** [comment]
you are right the link should reference solo-io/squash and not solo-io/squash-initial - I believe I fixed it. thanks for letting us know.
